name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  test:
    if: |
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'test:unit') ||
      contains(github.event.pull_request.labels.*.name, 'test:local')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["310", "311", "312"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pre-commit/action@v3.0.0

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.60.0

      - name: Run tests (pytest)
        run: |
          pixi run --manifest-path pixi.toml pytest-${{ matrix.python-version }}
